module.exports = {
  plugins: [
    'jest',
  ],
  env: {
    'jest/globals': true,
  },
  rules: {
    'jest/consistent-test-it': [2, { 'fn': 'it' }],
    'jest/expect-expect': 2,
    'jest/lowercase-name': 2,
    'jest/no-alias-methods': 0,
    'jest/no-commented-out-tests': 2,
    'jest/no-disabled-tests': 2,
    'jest/no-duplicate-hooks': 2,
    'jest/no-expect-resolves': 2,
    'jest/no-export': 2,
    'jest/no-focused-tests': 2,
    'jest/no-hooks': 0,
    'jest/no-identical-title': 2,
    'jest/no-if': 2,
    'jest/no-jasmine-globals': 2,
    'jest/no-jest-import': 2,
    'jest/no-large-snapshots': 0,
    'jest/no-mocks-import': 2,
    'jest/no-standalone-expect': 2,
    'jest/no-test-callback': 2,
    'jest/no-test-prefixes': 2,
    'jest/no-test-return-statement': 2,
    'jest/no-truthy-falsy': 2,
    'jest/no-try-expect': 2,
    'jest/prefer-called-with': 0,
    'jest/prefer-expect-assertions': 0,
    'jest/prefer-hooks-on-top': 2,
    'jest/prefer-inline-snapshots': 0,
    'jest/prefer-spy-on': 2,
    'jest/prefer-strict-equal': 2,
    'jest/prefer-to-be-null': 2,
    'jest/prefer-to-be-undefined': 2,
    'jest/prefer-to-contain': 2,
    'jest/prefer-to-have-length': 2,
    'jest/prefer-todo': 2,
    'jest/require-top-level-describe': 2,
    'jest/require-to-throw-message': 2,
    'jest/valid-describe': 2,
    'jest/valid-expect-in-promise': 2,
    'jest/valid-expect': [2, { 'alwaysAwait': true }],
    'jest/valid-title': 2,
  },
}
