name: Main

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-workflows:
    name: Check workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: download-actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/7fdc9630cc360ea1a469eed64ac6d78caeda1234/scripts/download-actionlint.bash) 1.6.25
        shell: bash
      - name: Check workflow files
        run: ${{ steps.download-actionlint.outputs.executable }} -color
        shell: bash

  analyse-code:
    name: Code scanner
    needs: check-workflows
    uses: ./.github/workflows/security-code-scanner.yml
    permissions:
      actions: read
      contents: read
      security-events: write
    secrets:
      SECURITY_SCAN_METRICS_TOKEN: ${{ secrets.SECURITY_SCAN_METRICS_TOKEN }}
      APPSEC_BOT_SLACK_WEBHOOK: ${{ secrets.APPSEC_BOT_SLACK_WEBHOOK }}

  lint-test:
    name: Lint and test
    needs: check-workflows
    uses: ./.github/workflows/lint-test.yml

  is-release:
    name: Determine whether this is a release merge commit
    needs: lint-test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      IS_RELEASE: ${{ steps.is-release.outputs.IS_RELEASE }}
    steps:
      - id: is-release
        uses: MetaMask/action-is-release@v2
        with:
          commit-starts-with: 'Release [version],Release v[version],Release/[version],Release/v[version],Release `[version]`'

  publish-release:
    name: Publish release
    needs: is-release
    if: needs.is-release.outputs.IS_RELEASE == 'true'
    permissions:
      contents: write
    uses: ./.github/workflows/publish-release.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  all-jobs-complete:
    name: All jobs complete
    runs-on: ubuntu-latest
    needs:
      - analyse-code
      - lint-test
    outputs:
      passed: ${{ steps.set-output.outputs.passed }}
    steps:
      - name: Set passed output
        id: set-output
        run: echo "passed=true" >> "$GITHUB_OUTPUT"

  all-jobs-pass:
    name: All jobs pass
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: all-jobs-complete
    steps:
      - name: Check that all jobs have passed
        run: |
          passed="${{ needs.all-jobs-complete.outputs.passed }}"
          if [[ $passed != "true" ]]; then
            exit 1
          fi
